NBCZ.Web/Areas/Admin/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using NBCZ.BLL;
using NBCZ.Model;
using Newtonsoft.Json;
namespace NBCZ.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class DepartmentController : BaseAdminController
    {
        Pub_DepartmentBLL deptBLL = new Pub_DepartmentBLL();
        FSRep rep = new FSRep()
        {
            errorNo = "0",
            results = new FSRepResult()
        };

        // GET: /Admin/Department/
       [Authorization(new string[] { DepartmentAuth.LIST, DepartmentAuth.ADD, DepartmentAuth.EDIT, DepartmentAuth.REMOVE})]
        public ActionResult Index(string selectNode="D000001")
        {
            ViewBag.selectNode = selectNode;
            return View();
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="parentCode"></param>
        /// <param name="parentName"></param>
        /// <returns></returns>
       [Authorization(new string[] { DepartmentAuth.ADD })]
        public ActionResult Add(string parentCode,string parentName)
        {
            ViewBag.parentName = parentName;
            ViewBag.parentCode = parentCode;
            return View();
        }

        [HttpPost]
        public ActionResult Add(Pub_Department model)
        {
            model.DeptCode = deptBLL.GetCode();
            model.StopFlag = false;
            model.Lmdt = DateTime.Now;
            model.ParentCode = Request["ids"];
            model.Lmid = NBCZUser.UserCode + "-" + NBCZUser.UserName;
         
            if (string.IsNullOrEmpty(model.ParentCode))
            {
                rep.errorNo = "-1";
                rep.errorInfo = "父节点不能为空！";
            }

            var r = deptBLL.Insert(model);
            if (!string.IsNullOrEmpty(r))
            {
                rep.results.data = model.ParentCode;
                rep.errorInfo = "添加成功";     
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "添加失败";
            }
            return Json(rep);
        }

        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="parentCode"></param>
        /// <param name="parentName"></param>
        /// <returns></returns>
        [Authorization(new string[] { DepartmentAuth.EDIT })]
        public ActionResult Edit(string DeptCode)
        {
            var model= deptBLL.Get(DeptCode);
            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(Pub_Department model)
        {
            model.StopFlag = false;
            model.Lmdt = DateTime.Now;
            model.ParentCode = Request["ids"];
            model.Lmid = NBCZUser.UserCode + "-" + NBCZUser.UserName;
            if (model.DeptCode=="D000001")
            {
                model.ParentCode = "";
            }
            else
            {
                if (string.IsNullOrEmpty(model.ParentCode))
                {
                    rep.errorNo = "-1";
                    rep.errorInfo = "父节点不能为空！";
                }
            }

            var r = deptBLL.Update(model);
            if (r)
            {
                rep.results.data = model.DeptCode;
                rep.errorInfo = "修改成功";
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "修改失败";
            }
            return Json(rep);
        }


        /// <summary>
        ///  部门树下拉框
        /// </summary>
        /// <param name="selectNode">默认选中的节点code</param>
        /// <param name="isRequired">是否必填</param>
        /// <param name="isMul">多选</param>
        /// <returns></returns>
        public ActionResult DeptTreeSelect(string selectNode,bool isRequired=true,bool isMul=false) 
        {
            ViewBag.isRequired = isRequired;
            ViewBag.selectNode = selectNode;
            ViewBag.isMul = isMul;
            ViewBag.DeptTreeData =JsonConvert.SerializeObject(GetDeptTreeFSTree());
            return View();
        }

        /// <summary>
        /// 获取部门列表树数据
        /// </summary>
        /// <returns></returns>
        public JsonResult GetDeptTree() 
        {
            string sqlstring = Request["where"];

            rep.results.data = GetDeptTreeFSTree();

            return Json(rep,JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// 获取部门列表树数据
        /// </summary>
        /// <returns></returns>

        private List<FSTree> GetDeptTreeFSTree()
        {
           var data= deptBLL.GetList(" StopFlag=0 ");
           List<FSTree> trees = new List<FSTree>();
           if (data==null||data.Count<=0)
           {
               return trees;
           }

           foreach (var item in data)
           {
               FSTree tree = new FSTree();
               tree.id = item.DeptCode;
               tree.isParent = string.IsNullOrEmpty(item.ParentCode) ? "true" : "false";
               tree.pId = item.ParentCode;
               tree.open = "true";
               tree.name = item.DeptName;
               trees.Add(tree);
           }

           return trees;

        }


        /// <summary>
        /// 获取子部门列表
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult GetChildList(string menuId)
        {

            rep.results.data = deptBLL.GetList(string.Format(" StopFlag=0 And DeptCode IN (Select DeptCode From f_SearchChildDept('{0}'))", menuId)," DeptCode ");

            return Json(rep);
        }


        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="deptCode"></param>
        /// <returns></returns>
        [Authorization(new string[] { DepartmentAuth.REMOVE })]
        public JsonResult DeleteBatch(string deptCode) 
        {
            if (string.IsNullOrEmpty(deptCode))
            {
                rep.errorNo = "-1";
                rep.errorInfo = "未选择删除的记录！";
                return Json(rep);
            }
            var list = new List<Pub_Department>();
            var r = deptBLL.ChangeSotpStatus("DeptCode in @DeptCode", new { DeptCode = deptCode.Split(',') });

            if (r)
            {
                rep.errorInfo = "删除成功";
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "删除失败";
            }

            return Json(rep);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="deptCode"></param>
        /// <returns></returns>
        [Authorization(new string[] { DepartmentAuth.REMOVE })]
        public JsonResult Delete(string deptCode)
        {
            if (string.IsNullOrEmpty(deptCode))
            {
                rep.errorNo = "-1";
                rep.errorInfo = "未选择删除的记录！";
                return Json(rep);
            }
            var r = deptBLL.ChangeSotpStatus("DeptCode=@DeptCode", new { DeptCode = deptCode });

            if (r)
            {
                rep.errorInfo = "删除成功";
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "删除失败";
            }

            return Json(rep);
        }
	}
}

NBCZ.Web/Areas/Admin/Controllers/UserController.cs

using NBCZ.BLL;
using NBCZ.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace NBCZ.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class UserController : BaseAdminController
    {
        private Pub_UserBLL userBLL = new Pub_UserBLL();
        private V_PubUser_DeptBLL userDeptBLL = new V_PubUser_DeptBLL();
        private Pub_UserRoleBLL userRoleBLL = new Pub_UserRoleBLL();
        private Pub_RoleBLL roleBLL = new Pub_RoleBLL();
        private Pub_FunctionBLL functionBLL = new Pub_FunctionBLL();
        private Pub_UserFunctionBLL userFunctionBLL = new Pub_UserFunctionBLL();

        FSRep rep = new FSRep()
        {
            errorNo = "0",
            results = new FSRepResult()
        };

        // GET: /Admin/User/
        [Authorization(new string[] { UserInfoAuth.LIST, UserInfoAuth.ADD, UserInfoAuth.EDIT, UserInfoAuth.REMOVE, UserInfoAuth.AUTH })]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取用户分页
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetPage(int pageNum = 1, int pageSize = 10, string field = "id", string order = " desc ")
        {
            var users = userDeptBLL.GetPage(GetWhereStr(), (field + " " + order), pageNum, pageSize);

            var usersData = users.data;
            var roles = userRoleBLL.GetUserRoles(" UserCode in  @UserCode", new { RoleCode = usersData.Select(p => p.UserCode) });

            foreach (var item in usersData)
            {
                var itemRoles = roles.Where(p => p.UserCode == item.UserCode);
                item.RoleCodes = string.Join(",", itemRoles.Select(p => p.RoleCode));
                item.RoleNames = string.Join(",", itemRoles.Select(p => p.RoleName));
            }
            FSRep rep = users.MapTo<V_PubUser_Dept>();
            return Json(rep);
        }

        //分页搜索
        private string GetWhereStr()
        {
            StringBuilder sb = new StringBuilder(" 1=1 ");
            sb.Append(" and StopFlag=0 ");

            var deptCode = Request["ids"];
            if (!string.IsNullOrEmpty(deptCode))
            {
                sb.AppendFormat(" and DeptCode='{0}' ", deptCode);
            }
            var createDate = Request["createDate"];
            if (!string.IsNullOrEmpty(createDate))
            {
                var arr = createDate.Split('~');
                var fromDate = arr[0];
                var toDate = arr[1];
                sb.AppendFormat("and Lmdt>='{0}' and Lmdt<='{1} 23:59:59' ", fromDate, toDate);
            }

            sb.AppendFormat(" and {0} ", this.HttpContext.GetWhereStr());

            return sb.ToString();
        }


        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="parentCode"></param>
        /// <param name="parentName"></param>
        /// <returns></returns>
        [Authorization(new string[] { UserInfoAuth.ADD })]
        public ActionResult Add()
        {
            ViewBag.Roles = GetRolesSelect();
            return View();
        }

        [HttpPost]
        public ActionResult Add(Pub_User model, FormCollection form)
        {
            model.UserCode = userBLL.GetCode();
            model.StopFlag = false;
            model.Lmdt = model.Crdt = DateTime.Now;
            model.DeptCode = form["ids"];
            model.Lmid = model.Crid = NBCZUser.UserCode + "-" + NBCZUser.UserName;
            model.UserName = model.UserName.Trim();
            if (IsUserNameRepeat(model.UserName))
            {
                rep.errorNo = "-1";
                rep.errorInfo = "用户名不能重名,请重新输入";
                return Json(rep);
            }
            var r = userBLL.Insert(model);
            if (r != null)
            {
                //插用户角色表
                var roles = form["Roles[]"].ToString().Split(',');
                AddUserRoles(model.UserCode, roles);

                rep.results.data = model.UserCode;
                rep.errorInfo = "添加成功";
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "添加失败";
            }
            return Json(rep);
        }


        /// <summary>
        /// 检查用户名是否重复
        /// </summary>
        /// <param name="p"></param>
        /// <returns></returns>
        private bool IsUserNameRepeat(string userName)
        {
            var list = userBLL.GetList(string.Format("UserName='{0}'", userName), limits: 1);
            return (list != null && list.Count >= 1);
        }

        //添加用户角色
        private void AddUserRoles(string userCode, string[] roles)
        {
            List<Pub_UserRole> userRoles = new List<Pub_UserRole>();
            foreach (var item in roles)
            {
                userRoles.Add(new Pub_UserRole { UserCode = userCode, RoleCode = item });
            }
            if (userRoles.Count > 0)
            {
                userRoleBLL.InsertBatch(userRoles);
            }
        }

        public IEnumerable<SelectListItem> GetRolesSelect(List<string> selectRoles = null)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var data = roleBLL.GetList(" StopFlag=0 ");
            foreach (var item in data)
            {
                SelectListItem model = new SelectListItem()
                {
                    Text = item.RoleName,
                    Value = item.RoleCode
                };
                if (selectRoles != null)
                {
                    model.Selected = selectRoles.Contains(item.RoleCode);
                }


                list.Add(model);
            }

            return list;

        }

        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="parentCode"></param>
        /// <param name="parentName"></param>
        /// <returns></returns>
        [Authorization(new string[] { UserInfoAuth.EDIT })]
        public ActionResult Edit(int id)
        {
            var model = userBLL.Get(id);
            var userRoles = userRoleBLL.GetList(string.Format("UserCode='{0}'", model.UserCode)).Select(p => p.RoleCode);
            ViewBag.Roles = GetRolesSelect(userRoles.ToList());
            ViewBag.UserRoleCodes = string.Join(",", userRoles);
            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(Pub_User model, FormCollection form)
        {
            model.Lmdt = DateTime.Now;
            model.Lmid = NBCZUser.UserCode + "-" + NBCZUser.UserName;
            model.DeptCode = form["ids"];
            model.UserName = model.UserName.Trim();
            if (form["oldUserName"] != model.UserName)
            {
                if (IsUserNameRepeat(model.UserName))
                {
                    rep.errorNo = "-1";
                    rep.errorInfo = "用户名不能重名,请重新输入";
                    return Json(rep);
                }
            }
            var r = userBLL.Update(model);
            if (r)
            {
                //角色已修改
                if (form["UserRoleCodes"] != form["Roles1[]"])
                {
                    r = userRoleBLL.DeleteByWhere("UserCode='" + model.UserCode + "'");
                    //插用户角色表
                    var roles = form["Roles1[]"].ToString().Split(',');
                    AddUserRoles(model.UserCode, roles);

                }

                rep.results.data = model.Id;
                rep.errorInfo = "修改成功";
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "修改失败";
            }
            return Json(rep);
        }


        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="deptCode"></param>
        /// <returns></returns>
        [Authorization(new string[] { UserInfoAuth.REMOVE })]
        public JsonResult DeleteBatch(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                rep.errorNo = "-1";
                rep.errorInfo = "未选择删除的记录！";
                return Json(rep);
            }
            var list = new List<Pub_Department>();
            var r = userBLL.ChangeSotpStatus("Id in @Id", new { Id = id.Split(',') });

            if (r)
            {
                rep.errorInfo = "删除成功";
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "删除失败";
            }

            return Json(rep);
        }

        [Authorization(new string[] { UserInfoAuth.REMOVE })]
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="deptCode"></param>
        /// <returns></returns>
        public JsonResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                rep.errorNo = "-1";
                rep.errorInfo = "未选择删除的记录！";
                return Json(rep);
            }
            var r = userBLL.ChangeSotpStatus("Id=@Id", new { Id = id });

            if (r)
            {
                rep.errorInfo = "删除成功";
            }
            else
            {
                rep.errorNo = "-1";
                rep.errorInfo = "删除失败";
            }

            return Json(rep);
        }

        /// <summary>
        /// 用户授权
        /// </summary>
        /// <param name="userCode"></param>
        /// <returns></returns>
        [Authorization(new string[] { UserInfoAuth.AUTH })]
        public ViewResult UserFunctionEdit(string userCode)
        {
            ViewBag.UserCode = userCode;

NBCZ.Web/Areas/Admin/Views/User/Add.cshtml
@model NBCZ.Model.Pub_User
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>

    <link href="~/fsLayui/css/layui-select-multiple.css" rel="stylesheet" />
    @Styles.Render("~/fsLayui/css")
    @Scripts.Render("~/fsLayui/js")
    @Scripts.Render(new string[] { "~/fsLayui/plugins/frame/js/frame.js" })
    <!--树-->
    <link href="~/fsLayui/plugins/ztree/css/zteeSelect.css" rel="stylesheet" />
    <script src="~/fsLayui/plugins/ztree/js/ztreeSelect.js"></script>
</head>
<body>
    <div class="layui-fluid">
       <form class="layui-form" isload="1" isUrlParamRender="0">
            <div class="layui-form-item">
                <label class="layui-form-label">用户名：</label>
                <div class="layui-input-inline">
                    <input type="text" name="UserName" required="" lay-verify="required" placeholder="请输入昵称" class="layui-input" />
                </div>
                <label class="layui-form-label">密码：</label>
                <div class="layui-input-inline">
                    <input type="password" name="UserPwd"  lay-verify="required" placeholder="请输入密码" class="layui-input" />
                </div>

            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">电话：</label>
                <div class="layui-input-inline">
                    <input type="text" name="Tel" required="" placeholder="请输入电话" maxlength="20" class="layui-input" />
                </div>
                <label class="layui-form-label">部门：</label>
                <div class="layui-input-inline">
                    @Html.Action("DeptTreeSelect", "Department")
                </div>
                
            </div>
           <div class="layui-form-item">
               <label class="layui-form-label">姓名：</label>
               <div class="layui-input-inline">
                   <input type="text" name="RealName" placeholder="请输入姓名" class="layui-input" />
               </div>
               <label class="layui-form-label" style="padding-top:8px;">性别：</label>
               <div class="layui-input-inline">
                   <input type="radio" name="Sex" value="True" title="男" checked="">
                   <input type="radio" name="Sex" value="False" title="女">
               </div>
           
                   @*<input type="text" name="RoleCodes"  placeholder="请输入姓名" class="layui-input" />*@
               </div>
           
           <div class="layui-form-item">
               <label class="layui-form-label">角色：</label>
               <div class="layui-input-block">
                   @Html.DropDownList("Roles", ViewBag.Roles as IEnumerable<SelectListItem>,"请选择", new { @lay_verify = "required", multiple = "multiple", @lay_search = "lay_search" })
               </div>
            </div>
           <div class="layui-form-item">
               <label class="layui-form-label">地址：</label>
               <div class="layui-input-block">
                   <input type="text" name="UserAddress" placeholder="请输入地址"  class="layui-input" maxlength="100" />
               </div>
           </div>
            <div class="layui-form-item layui-form-text">
                <label class="layui-form-label">备注：</label>
                <div class="layui-input-block">
                    <textarea name="Remark" placeholder="请输入备注" class="layui-textarea" maxlength="100"></textarea>
                </div>
            </div>
            <hr />
            <div class="layui-form-item">
                <div class="layui-input-block">
                    @*topredirecturl="@Url.ActionAdmin("Index", new { selectNode = ViewBag.parentCode })"*@
                    <button class="layui-btn" lay-submit="" method="post" url="@Url.ActionAdmin("Add")">新增</button>
                    <button type="button" class="layui-btn layui-btn-primary" function="close">关闭</button>
                </div>
            </div>

            <input type="hidden" name="ParentName" value="@ViewBag.parentName" />
           </form>
    </div>

</body>
</html>


NBCZ.Web/Areas/Admin/Views/User/Edit.cshtml
@model NBCZ.Model.Pub_User
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>

    <link href="~/fsLayui/css/layui-select-multiple.css" rel="stylesheet" />
    @Styles.Render("~/fsLayui/css")
    @Scripts.Render("~/fsLayui/js")
    @Scripts.Render(new string[] { "~/fsLayui/plugins/frame/js/frame.js" })
    <!--树-->
    <link href="~/fsLayui/plugins/ztree/css/zteeSelect.css" rel="stylesheet" />
    <script src="~/fsLayui/plugins/ztree/js/ztreeSelect.js"></script>
</head>
<body>
    <div class="layui-fluid">
        <form class="layui-form" isload="1" isurlparamrender="0">
            <div class="layui-form-item">
                <label class="layui-form-label">用户名：</label>
                <div class="layui-input-inline">
                    <input type="text" name="UserName" value="@Model.UserName" required="" lay-verify="required" placeholder="请输入昵称" class="layui-input" />
                </div>
                <label class="layui-form-label">密码：</label>
                <div class="layui-input-inline">
                    <input type="password" name="UserPwd" value="@Model.UserPwd" lay-verify="required" placeholder="请输入密码" class="layui-input" />
                </div>

            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">电话：</label>
                <div class="layui-input-inline">
                    <input type="text" name="Tel" value="@Model.Tel" required="" placeholder="请输入电话" maxlength="20" class="layui-input" />
                </div>
                <label class="layui-form-label">部门：</label>
                <div class="layui-input-inline">
                    @Html.Action("DeptTreeSelect", "Department", new { selectNode=Model.DeptCode})
                </div>

            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">姓名：</label>
                <div class="layui-input-inline">
                    <input type="text" name="RealName" value="@Model.RealName" placeholder="请输入姓名" class="layui-input" />
                </div>
                <label class="layui-form-label" style="padding-top:8px;">性别：</label>
                <div class="layui-input-inline">
                    <input type="radio" name="Sex" value="True" title="男" @(Model.Sex?"checked":"") />
                    <input type="radio" name="Sex" value="False" title="女" @(!Model.Sex ? "checked" : "")>
                </div>

                @*<input type="text" name="RoleCodes"  placeholder="请输入姓名" class="layui-input" />*@
            </div>

            <div class="layui-form-item">
                <label class="layui-form-label">角色：</label>
                <div class="layui-input-block">
                    @Html.DropDownList("Roles1", (IEnumerable<SelectListItem>)ViewBag.Roles, "请选择", new { @lay_verify = "required", multiple = "multiple", @lay_search = "lay_search", })
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">地址：</label>
                <div class="layui-input-block">
                    <input type="text" name="UserAddress" value="@Model.UserAddress" placeholder="请输入地址" class="layui-input" maxlength="100" />
                </div>
            </div>
            <div class="layui-form-item layui-form-text">
                <label class="layui-form-label">备注：</label>
                <div class="layui-input-block">
                    <textarea name="Remark" placeholder="请输入备注" class="layui-textarea" maxlength="100">@Model.Remark</textarea>
                </div>
            </div>
            <hr />
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit="" method="post" url="@Url.ActionAdmin("Edit")">编辑</button>
                    <button type="button" class="layui-btn layui-btn-primary" function="close">关闭</button>
                </div>
            </div>
            <input type="hidden" name="UserRoleCodes" value="@ViewBag.UserRoleCodes" />
            @Html.HiddenFor(p=>p.Id)
            @Html.HiddenFor(p => p.UserCode)
            @Html.Hidden("oldUserName",Model.UserName)
        </form>
    </div>

</body>
</html>

NBCZ.Web/Areas/Admin/Views/User/EditPassWord.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>

    <link href="~/fsLayui/css/layui-select-multiple.css" rel="stylesheet" />
    @Styles.Render("~/fsLayui/css")
    @Scripts.Render("~/fsLayui/js")
    @Scripts.Render(new string[] { "~/fsLayui/plugins/frame/js/frame.js" })
    <!--树-->
    <link href="~/fsLayui/plugins/ztree/css/zteeSelect.css" rel="stylesheet" />
    <script src="~/fsLayui/plugins/ztree/js/ztreeSelect.js"></script>
</head>
<body>
    <div class="layui-fluid">
        <form class="layui-form" isload="1" isurlparamrender="0" >
            <div class="layui-form-item">
                <label class="layui-form-label">原密码：</label>
                <div class="layui-input-block">
                    <input type="password" name="OldPassWord" required="" lay-verify="required" placeholder="请输入原密码" autocomplete="off" class="layui-input" />
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">新密码：</label>
                <div class="layui-input-block">
                    @*lay-vertype="tips" 提示类型*@
                    <input type="password" id="PassWord" name="PassWord" equalsid="PassWord2" equalsmsg="两次输入密码不一致" required="" lay-verify="required|equals" placeholder="请输入新密码" autocomplete="off" class="layui-input" />
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">重复新密码：</label>
                <div class="layui-input-block">
                    <input type="password" id="PassWord2" name="PassWord2" required="" lay-verify="required" placeholder="请重复新密码" autocomplete="off" class="layui-input" />
                </div>
            </div>
            <hr />
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" id="btnSub"  lay-submit="" method="post" calljs="onSuccess" url="@Url.ActionAdmin("EditPassWord")">编辑</button>
                    <button type="button" class="layui-btn layui-btn-primary" function="close">关闭</button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        layui.use(['layer'], function () {
            var layer = layui.layer;
            window.onSuccess = function (rep) {
                if (rep.errorNo == "0") {
                    layer.msg('修改成功！将调至登录页面...',{
                        icon: 1,
                        time: 2000 //2秒关闭（如果不配置，默认是3秒）
                     }, function () {
                        window.top.location.href = "../Login/Index";
                     })
                    return false;//将不执行fslayui后续代码
                }

            }
        })

    </script>
</body>
</html>

NBCZ.Web/Areas/Admin/Views/User/UserFunctionEdit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserFunction</title>
    @Styles.Render("~/fsLayui/css")
</head>
<body>
    <div class="layui-fluid" >
        <form class="layui-form" isload="1" isurlparamrender="0">
            <div class="layui-form-item" >
                <fieldset class="layui-elem-field">
                    <legend style="font-size:14px;">权限列表</legend>
                    <div class="layui-field-box" style="height:420px;overflow-y:auto;">
                        <div class="layui-row layui-col-space10">
                            <div class="layui-col-md12">
                                <ul id="treeDemo" class="ztree fsTree" icon="" method="post" checktype="checkbox" selectnode="@ViewBag.selectNode" isroot="0" gettree="01" url="@Url.Action("GetUserFunctionTree", new { area = "Admin", userCode =ViewBag.UserCode })" treeidkey="id" treepidkey="pId" treename="name"></ul>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit="" method="post" onclick="saveBefore()" url="@Url.ActionAdmin("UserFunctionEdit")">保存</button>
                    <button type="button" class="layui-btn layui-btn-primary" function="close">关闭</button>
                </div>
            </div>
            <input type="hidden" id="selectValues" name="selectValues" value="@ViewBag.selectNode" />
            <input type="hidden" id="userCode" name="userCode" value="@ViewBag.UserCode" />
        </form>
        @Scripts.Render("~/fsLayui/js")
        @Scripts.Render(new string[] { "~/fsLayui/plugins/frame/js/frame.js" })
        <script type="text/javascript">
            function saveBefore() {
                var treeObj = $.fn.zTree.getZTreeObj("treeDemo");
                var nodes = treeObj.getCheckedNodes(true);
                var vals = "";
                for (var i = 0; i < nodes.length; i++) {
                    vals += nodes[i].id + ',';
                }
                vals = vals.substring(0, vals.length - 1);
                $("#selectValues").val(vals);
            }
        </script>
    </div>
</body>
</html>